apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-qiagssml
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-qiagssml 
  name: go-qiagssml
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-qiagssml
    weight: 100 
